#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/usr/local/lib/python3.7/dist-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/usr/local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/content/drive/MyDrive/Stylized-Cell-model/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
