#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/local"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/local/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/drfrbc/Hay&Segev2015/x86_64/.libs/libnrnmech.so" "$@"
